#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proxy

resources:
- proxy-namespace.yaml
- proxy-config.yaml
- proxy-deployment.yaml
- proxy-service.yaml

