#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:  <FIXME: copied from router-default>
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
  - name: port-9092
    protocol: TCP
    port: 9092
    targetPort: 9092

